### ISSUE TITLE
Non train_hook module

### ISSUE THREAD

**Issue by ZiningWang** [jeasinema/tf_voxelnet#1]
Traceback (most recent call last):
  File "train.py", line 21, in <module>
    from train_hook import check_if_should_pause
ImportError: No module named 'train_hook'

Could not find train_hook anywhere else

**Comment by MilPat555** [comment]
I have ran into the same problem. 

Also have a problem in utils.py importing box_overlaps * 
Throws 'ModuleNotFoundError: No module named 'box_overlaps'.

Also, is  there a purpose for scattered *'s in front of feature_map_shape? They throw syntax errors so I removed them.

**Comment by jeasinema** [comment]
@ZiningWang Sorry, and I just add this in `9138855`, you can merge this latest commit to your local repo.
@MilPat555 I'm not sure if you are using `Python2.x`. Since this code can only run under `Python3.5+`, so this syntax error may due to this.
