### ISSUE TITLE
RPN last layer 

### ISSUE THREAD

**Issue by ZiningWang** [jeasinema/tf_voxelnet#10]
I notice you use the relu layer for the last layer of RPN which predicts class score and regression. However, as far as I know, the last layer of RPN should not use Relu. For example, if you want to shrink your anchor, you must have some negative prediction in regression.

The paper says 'BN and relu for all conv' but I doubt it is not applied at least for the last map.

**Comment by jeasinema** [comment]
Many thanks for this issue. Fix at jeasinema/tf_voxelnet@a7a2729.
