### ISSUE TITLE
ValueError: cannot convert float NaN to integer

### ISSUE THREAD

**Issue by szm88** [jeasinema/tf_voxelnet#13]
when I run test.py:
FailedPreconditionError (see above for traceback): Attempting to use uninitialized value MiddleAndRPN_/conv7/kernel

**Comment by jeasinema** [comment]
Please provide more information about this error, like how to reproduce it.

**Comment by xueyingliu** [comment]
@szm88 I got similar problem when run test.py:
the ret_box3d got a TypeError: 'NoneType' object is not iterable
can you tell me how do you deal with your error? Thank you so much~
