### ISSUE TITLE
Bus error:10 at random times during beginning of training

### ISSUE THREAD

**Issue by MilPat555** [jeasinema/tf_voxelnet#2]
Hey, 

I am trying to train your neural network on the KITTI dataset, but I have run into this error "Bus error: 10" which is associated with the code trying to read and invalid memory location, but cannot seem to figure out why. 

I got the error initially because I did not have a "testing" folder set up while trying to train and I would get the error immediately. 
But after doing so and populating it with some data, it started to run but this error gets thrown at random times within the first 7 steps. 

Does the training try to read anything else specific which I may be missing?

Also, I only have a single GPU so I lowered the number in the config, which is why it is only training on 1 file. 

Thank you very much

![image](https://user-images.githubusercontent.com/28031163/34179377-a55d1e74-e4d8-11e7-9655-75d07022d2c0.png)

**Comment by jeasinema** [comment]
I think you can just checkout jeasinema/tf_voxelnet@2cc0cfd to totally remove the support for multi-gpu training. Or you can try to decrease the `parallel_iteration` in [group_pointcloud.py:83](https://github.com/jeasinema/tf_voxelnet/blob/master/group_pointcloud.py#L83)
